const paginaWeb = {
    titulo: 'Los Cuatro Dioses del Cielo y la Tierra',
    subtitulo: 'Historia de las deidades protectoras de Kyoto',
    descripcion: 'En la mitología de Japón los Cuatro Puntos Cardinales están guardados por las cuatro Bestias Sagradas, animales de origen divino y cuyo origen encontramos en las representaciones chinas de las constelaciones, compartiendo algunos rasgos en ambas culturas. Su función en la cultura japonesa es la de proteger los cuatro costados de la ciudad de Kyoto, y en ella tienen diversos templos dedicados como muestra de su importancia. Veamos también las similitudes que existen con la mitología china. Suzaku: Es el ave Fénix que guarda la ciudad de Kyoto desde el Sur y simboliza tanto el Fuego como el Verano, siendo representado en la mayoría de ocasiones como un brillante pájaro de color magenta y cubierto de llamas. En la cultura de China se le conoce como el Ave Bermellón e incluso tiene su propia constelación en el cielo nocturno. Genbu: Es el guardián del Norte y se le suele representar como una serpiente que se enrosca alrededor de una tortuga, simbolizando el elemento Tierra y el Invierno. Dentro de la mitología china es conocido como la «Tortuga Negra» o el «Guerrero Negro» y para ellos representa la protección del hogar y la longevidad. Byakko: Su nombre se puede traducir como «Luz Blanca» y tiene el aspecto de un gran tigre blanco es el guardián del Oeste y representa la estación del Otoño y el elemento Aire. La tradición nos cuenta que es capaz de emitir un poderoso rugido con el que atrae las tormentas y tempestades. Dentro de la mitología china es el señor y amo de todas las bestias y que su blanco pelaje es muestra de su longevidad, ya que las leyendas dicen que cuando un tigre alcanza los 500 años de edad su pelo se vuelve completamente blanco. Seiryu: Es un gran dragón de color azul que protege Kyoto desde el Este y representa tanto al elemento Agua como a la Primavera. Una curiosidad sobre el Dragón Azul es que posee un templo dedicado (Kiyomizu) en cuyo interior hay una fuente de la que se debe beber a medianoche, tras lo cual comienzan las ceremonias nocturnas en su honor. En China se le conoce como el «dragón azur» o también como «dragón azur del este»',
    autor: 'Juanjo',
    fechaCreacion: '12 de Enero de 2024',
    etiquetas: ["web", "mitología", "dioses", "japon", "kyoto"]
}

module.exports = paginaWeb;
